
--exercise
insert into exercise_index (id, exercise_name, exercise_index) values (1,'Crunches',20);
insert into exercise_index (id, exercise_name, exercise_index) values (2,'Walking',15);
insert into exercise_index (id, exercise_name, exercise_index) values (3,'Running',40);
insert into exercise_index (id, exercise_name, exercise_index) values (4,'Sprinting',60);
insert into exercise_index (id, exercise_name, exercise_index) values (5,'Squats',60);
insert into exercise_index (id, exercise_name, exercise_index) values (6,'Bench press',45);

--food
insert into food_index (id, food_name, glycemic_index) values (1,'Banana cake, made with sugar',47);
insert into food_index (id, food_name, glycemic_index) values (2,'Banana cake, made without sugar',55);
insert into food_index (id, food_name, glycemic_index) values (3,'Sponge cake, plain',46);
insert into food_index (id, food_name, glycemic_index) values (4,'Vanilla cake made from packet mix with vanilla frosting (Betty Crocker)',42);
insert into food_index (id, food_name, glycemic_index) values (5,'Apple, made with sugar',44);
insert into food_index (id, food_name, glycemic_index) values (6,'Apple, made without sugar',48);
insert into food_index (id, food_name, glycemic_index) values (7,'Waffles, Aunt Jemima (Quaker Oats)',76);
insert into food_index (id, food_name, glycemic_index) values (8,'Bagel, white, frozen',72);
insert into food_index (id, food_name, glycemic_index) values (9,'Baguette, white, plain',95);
insert into food_index (id, food_name, glycemic_index) values (10,'Coarse barley bread, 75-80% kernels, average',34);
insert into food_index (id, food_name, glycemic_index) values (11,'Hamburger bun',61);
insert into food_index (id, food_name, glycemic_index) values (12,'Kaiser roll',73);
insert into food_index (id, food_name, glycemic_index) values (13,'Pumpernickel bread',56);
insert into food_index (id, food_name, glycemic_index) values (14,'50% cracked wheat kernel bread',58);
insert into food_index (id, food_name, glycemic_index) values (15,'White wheat flour bread',71);
insert into food_index (id, food_name, glycemic_index) values (16,'Wonder™ bread, average',73);
insert into food_index (id, food_name, glycemic_index) values (17,'Whole wheat bread, average',71);
insert into food_index (id, food_name, glycemic_index) values (18,'100% Whole Grain bread (Natural Ovens)',51);
insert into food_index (id, food_name, glycemic_index) values (19,'Pita bread, white',68);
insert into food_index (id, food_name, glycemic_index) values (20,'Corn tortilla',52);
insert into food_index (id, food_name, glycemic_index) values (21,'Wheat tortilla',30);
insert into food_index (id, food_name, glycemic_index) values (23,'Coca Cola, average',63);
insert into food_index (id, food_name, glycemic_index) values (24,'Fanta, orange soft drink',68);
insert into food_index (id, food_name, glycemic_index) values (25,'Lucozade, original (sparkling glucose drink)',95);
insert into food_index (id, food_name, glycemic_index) values (26,'Apple juice, unsweetened, average',44);
insert into food_index (id, food_name, glycemic_index) values (27,'Cranberry juice cocktail (Ocean Spray)',68);
insert into food_index (id, food_name, glycemic_index) values (28,'Gatorade',78);
insert into food_index (id, food_name, glycemic_index) values (29,'Orange juice, unsweetened',50);
insert into food_index (id, food_name, glycemic_index) values (30,'Tomato juice, canned',38);
insert into food_index (id, food_name, glycemic_index) values (32,'All-Bran, average',55);
insert into food_index (id, food_name, glycemic_index) values (33,'Coco Pops, average',77);
insert into food_index (id, food_name, glycemic_index) values (34,'Cornflakes, average',93);
insert into food_index (id, food_name, glycemic_index) values (35,'Cream of Wheat (Nabisco)',66);
insert into food_index (id, food_name, glycemic_index) values (36,'Cream of Wheat, Instant (Nabisco)',74);
insert into food_index (id, food_name, glycemic_index) values (37,'Grapenuts, average',75);
insert into food_index (id, food_name, glycemic_index) values (38,'Muesli, average',66);
insert into food_index (id, food_name, glycemic_index) values (39,'Oatmeal, average',55);
insert into food_index (id, food_name, glycemic_index) values (40,'Instant oatmeal, average',83);
insert into food_index (id, food_name, glycemic_index) values (41,'Puffed wheat, average',80);
insert into food_index (id, food_name, glycemic_index) values (42,'Raisin Bran (Kelloggs)',61);
insert into food_index (id, food_name, glycemic_index) values (43,'Special K (Kelloggs)',69);
insert into food_index (id, food_name, glycemic_index) values (45,'Pearled barley, average',28);
insert into food_index (id, food_name, glycemic_index) values (46,'Sweet corn on the cob, average',60);
insert into food_index (id, food_name, glycemic_index) values (47,'Couscous, average',65);
insert into food_index (id, food_name, glycemic_index) values (48,'Quinoa',53);
insert into food_index (id, food_name, glycemic_index) values (49,'White rice, average',89);
insert into food_index (id, food_name, glycemic_index) values (50,'Quick cooking white basmati',67);
insert into food_index (id, food_name, glycemic_index) values (51,'Brown rice, average',50);
insert into food_index (id, food_name, glycemic_index) values (52,'Converted, white rice (Uncle Bens)',38);
insert into food_index (id, food_name, glycemic_index) values (53,'Whole wheat kernels, average',30);
insert into food_index (id, food_name, glycemic_index) values (54,'Bulgur, average',48);
insert into food_index (id, food_name, glycemic_index) values (56,'Graham crackers',74);
insert into food_index (id, food_name, glycemic_index) values (57,'Vanilla wafers',77);
insert into food_index (id, food_name, glycemic_index) values (58,'Shortbread',64);
insert into food_index (id, food_name, glycemic_index) values (59,'Rice cakes, average',82);
insert into food_index (id, food_name, glycemic_index) values (60,'Rye crisps, average',64);
insert into food_index (id, food_name, glycemic_index) values (61,'Soda crackers',74);
insert into food_index (id, food_name, glycemic_index) values (63,'Ice cream, regular',57);
insert into food_index (id, food_name, glycemic_index) values (64,'Ice cream, premium',38);
insert into food_index (id, food_name, glycemic_index) values (65,'Milk, full fat',41);
insert into food_index (id, food_name, glycemic_index) values (66,'Milk, skim',32);
insert into food_index (id, food_name, glycemic_index) values (67,'Reduced-fat yogurt with fruit, average',33);
insert into food_index (id, food_name, glycemic_index) values (69,'Apple, average',39);
insert into food_index (id, food_name, glycemic_index) values (70,'Banana, ripe',62);
insert into food_index (id, food_name, glycemic_index) values (71,'Dates, dried',42);
insert into food_index (id, food_name, glycemic_index) values (72,'Grapefruit',25);
insert into food_index (id, food_name, glycemic_index) values (73,'Grapes, average',59);
insert into food_index (id, food_name, glycemic_index) values (74,'Orange, average',40);
insert into food_index (id, food_name, glycemic_index) values (75,'Peach, average',42);
insert into food_index (id, food_name, glycemic_index) values (76,'Peach, canned in light syrup',40);
insert into food_index (id, food_name, glycemic_index) values (77,'Pear, average',38);
insert into food_index (id, food_name, glycemic_index) values (78,'Pear, canned in pear juice',43);
insert into food_index (id, food_name, glycemic_index) values (79,'Prunes, pitted',29);
insert into food_index (id, food_name, glycemic_index) values (80,'Raisins',64);
insert into food_index (id, food_name, glycemic_index) values (81,'Watermelon',72);
insert into food_index (id, food_name, glycemic_index) values (83,'Baked beans, average',40);
insert into food_index (id, food_name, glycemic_index) values (84,'Blackeye peas, average',33);
insert into food_index (id, food_name, glycemic_index) values (85,'Black beans',30);
insert into food_index (id, food_name, glycemic_index) values (86,'Chickpeas, average',10);
insert into food_index (id, food_name, glycemic_index) values (87,'Chickpeas, canned in brine',38);
insert into food_index (id, food_name, glycemic_index) values (88,'Navy beans, average',31);
insert into food_index (id, food_name, glycemic_index) values (89,'Kidney beans, average',29);
insert into food_index (id, food_name, glycemic_index) values (90,'Lentils, average',29);
insert into food_index (id, food_name, glycemic_index) values (91,'Soy beans, average',15);
insert into food_index (id, food_name, glycemic_index) values (92,'Cashews, salted',27);
insert into food_index (id, food_name, glycemic_index) values (93,'Peanuts, average',7);
insert into food_index (id, food_name, glycemic_index) values (95,'Fettucini, average',32);
insert into food_index (id, food_name, glycemic_index) values (96,'Macaroni, average',47);
insert into food_index (id, food_name, glycemic_index) values (97,'Macaroni and Cheese (Kraft)',64);
insert into food_index (id, food_name, glycemic_index) values (98,'Spaghetti, white, boiled, average',46);
insert into food_index (id, food_name, glycemic_index) values (99,'Spaghetti, white, boiled 20 min, average',58);
insert into food_index (id, food_name, glycemic_index) values (100,'Spaghetti, wholemeal, boiled, average',42);
insert into food_index (id, food_name, glycemic_index) values (102,'Corn chips, plain, salted, average',42);
insert into food_index (id, food_name, glycemic_index) values (103,'Fruit Roll-Ups',99);
insert into food_index (id, food_name, glycemic_index) values (104,'M & Ms, peanut',33);
insert into food_index (id, food_name, glycemic_index) values (105,'Microwave popcorn, plain, average',55);
insert into food_index (id, food_name, glycemic_index) values (106,'Potato chips, average',51);
insert into food_index (id, food_name, glycemic_index) values (107,'Pretzels, oven-baked',83);
insert into food_index (id, food_name, glycemic_index) values (108,'Snickers Bar',51);
insert into food_index (id, food_name, glycemic_index) values (111,'Carrots, average',35);
insert into food_index (id, food_name, glycemic_index) values (112,'Parsnips',52);
insert into food_index (id, food_name, glycemic_index) values (113,'Baked russet potato, average',111);
insert into food_index (id, food_name, glycemic_index) values (114,'Boiled white potato, average',82);
insert into food_index (id, food_name, glycemic_index) values (115,'Instant mashed potato, average',87);
insert into food_index (id, food_name, glycemic_index) values (116,'Sweet potato, average',70);
insert into food_index (id, food_name, glycemic_index) values (117,'Yam, average',54);
insert into food_index (id, food_name, glycemic_index) values (110,'Green peas, average',51);
insert into food_index (id, food_name, glycemic_index) values (119,'Hummus (chickpea salad dip)',6);
insert into food_index (id, food_name, glycemic_index) values (120,'Chicken nuggets, frozen, reheated in microwave oven 5 min',46);
insert into food_index (id, food_name, glycemic_index) values (121,'Pizza, plain baked dough, served with parmesan cheese and tomato sauce',80);
insert into food_index (id, food_name, glycemic_index) values (122,'Pizza, Super Supreme (Pizza Hut)',36);
insert into food_index (id, food_name, glycemic_index) values (123,'Honey, average',61);


